title: Tech & Stuff # The title of the blog
author: Dennis Miller # Your name 
email: kuriousfrank@gmail.com # your email shown in the footer
url: https://dennismiler.github.io # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Posts about technology or projects | videos I am currently working on.
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "http://via.placeholder.com/300x300" # avatar in about page
  about_you: Opinionated Software Engineer (uncanny). # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: 
    github:  dennismiler
    # rss: RSS
    # dribbble: 
    # facebook: huangyz0918
    # flickr:   
    # instagram: 
    # linkedin: yizheng-huang
    # pinterest: 
    # youtube: https://www.youtube.com/channel/UCToiUBcDp4U3mIyX3ldKmfA
    youtube_channel: UCToiUBcDp4U3mIyX3ldKmfA
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    reddit: dennismiler 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
